# Go Language development user specific setup.

# Start from base Ubuntu 14.04 LTS.
FROM godev/liteide
MAINTAINER Tom Hite <tdhite@gmail.us>

# Remove the need for apt-get (et al) confirmation
ENV DEBIAN_FRONTEND noninteractive

# Add my user
RUN useradd --create-home {{ user }}
RUN chsh -s /bin/bash {{ user }}

RUN echo "export PATH=${PATH}:/home/{{ user }}/bin" >> /etc/bash.bashrc
RUN echo "export USE_CCACHE=1" >> /etc/bash.bashrc
RUN echo "export GOPATH=/home/{{ user }}/go" >> /etc/bash.bashrc

# Setup AWS CLI, Git and VNC
ADD ./.aws /home/{{ user }}/.aws
ADD ./.netrc /home/{{ user }}/
ADD ./.ssh /home/{{ user }}/.ssh
ADD ./.vnc /home/{{ user }}/.vnc
RUN chmod 600 /home/{{ user }}/.aws/config /home/{{ user }}/.netrc /home/{{ user }}/.ssh/id_rsa /home/{{ user }}/.vnc/passwd
RUN chmod 775 /home/{{ user }}/.vnc/xstartup
ADD ./liteide.desktop /home/{{ user }}/.local/share/applications/

# Set ownership for the entire {{ user }} directory
RUN chown -R {{ user }}:{{ user }} /home/{{ user }}

# Expose the vnc port as display 0 (:0)
EXPOSE 5900

# attach the code base
VOLUME /home/{{ user }}/go
